/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-10 10:24:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mortgage.JdbcMortgageUtility;
import mortgage.MortgageProductBean;
import mortgage.MortgageTransactionBean;
import product.ProductBean;
import sale.SaleTransactionBean;
import customer.JdbcCustomerUtility;
import sale.JdbcSaleUtility;
import java.util.Iterator;
import java.util.ArrayList;
import customer.CustomerBean;
import search.CustomerSearchBean;

public final class customerdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1407531964000L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1407531964000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"A layout example with a side menu that hides on mobile, just like the Pure website.\">\r\n");
      out.write("\r\n");
      out.write("<title>Mangal &nbsp;Murti</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/colorbox.css\" />\r\n");
      out.write("<script src=\"js/offline-scripts/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.colorbox.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 8]>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/layouts/side-menu-old-ie.css\">\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layouts/side-menu.css\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("Global CSS -->.center-text {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".span-pad {\r\n");
      out.write("\tpadding: 0.4em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#scrollable-dropdown-menu .tt-dropdown-menu {\r\n");
      out.write("\tmax-height: 150px;\r\n");
      out.write("\toverflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-success,.button-error,.button-warning,.button-secondary {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\ttext-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-success {\r\n");
      out.write("\tbackground: rgb(28, 184, 65); /* this is a green */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\toverflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write("<!-- Global CSS End -->\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".center-text {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".span-pad {\r\n");
      out.write("\tpadding: 0.4em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t$(\".iframe\").colorbox({iframe:true, width:\"70%\", height:\"80%\"});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\t\t\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t\tvar x = \"\";\r\n");
      out.write("\t\tif (confirm(\"Do you want to logout ???\") == true) {\r\n");
      out.write("\t\t\twindow.location.replace(\"logout.jsp\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tx = \"You pressed Cancel!\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"demo\").innerHTML = x;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction pageEssentials() {\r\n");
      out.write("\t\tdocument.getElementById(\"search-link\").className = \"menu-item-divided pure-menu-selected\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteImagesFromDb(){\r\n");
      out.write("\t\tvar custID = ");
      out.print( request.getParameter("id"));
      out.write("\r\n");
      out.write("\t\tvar xmlhttp;\r\n");
      out.write("\t\tif (window.XMLHttpRequest) {\r\n");
      out.write("\t\t\txmlhttp = new XMLHttpRequest(); //for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\txmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\"); //for IE6, IE5\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\txmlhttp.open(\"GET\", \"deleteoldimages.jsp?id=\" + custID, true);\r\n");
      out.write("\t\txmlhttp.send(null);\r\n");
      out.write("\t\txmlhttp.onreadystatechange = function() {\r\n");
      out.write("\t\t\tif (xmlhttp.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlhttp.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar isSuccess = xmlhttp.responseText;\r\n");
      out.write("\t\t\t\t\tif(isSuccess)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\talert(\"Images deleted for Completed Mortgage\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\talert(\"Error deleting images\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"pageEssentials()\">\r\n");
      out.write("\t<div id=\"layout\">\r\n");
      out.write("\t\t<!-- Menu toggle -->\r\n");
      out.write("\t\t<a href=\"#menu\" id=\"menuLink\" class=\"menu-link\"> <!-- Hamburger icon -->\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Date JQuery Imports -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function dateChecker() {\r\n");
      out.write("\tvar something = document.getElementById(\"datepicker\").value;\r\n");
      out.write("\tvar something1 = document.getElementById(\"datepicker1\").value;\r\n");
      out.write("\tif(something == \"\" || something1 == \"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\talert('Please enter date !!!');\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("    $(\"#datepicker\").datepicker();\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("$(function() {\r\n");
      out.write("    $(\"#datepicker1\").datepicker();\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pure-min.css\">\r\n");
      out.write("<!-- Date JQuery Imports -->\r\n");
      out.write("\t");

		Boolean isloggedin = (Boolean) session.getAttribute("isloggedin");
		if(isloggedin == null || isloggedin == Boolean.FALSE)
		{
		    out.write("<script type='text/javascript'>\n");
		    out.write("alert(' Your session has expired. Please login again. ');\n");
		    out.write("setTimeout(function(){window.location.href='index.jsp'},0);");
		    out.write("</script>\n");	    
		}
	
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("\t<div class=\"pure-menu pure-menu-open\">\r\n");
      out.write("\t\t<a class=\"pure-menu-heading\"\r\n");
      out.write("\t\t\tstyle=\"text-transform: none; font-size: 120%\" href=\"#\">JewelTrack<sup>tm</sup></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"dashboard-link\"><a href=\"dashboard.jsp\" >Home</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"report-link\"><a href=\"report.jsp\" >Report</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"\" id=\"inventory-link\"><a href=\"inventory.jsp\" >Inventory</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"\" id=\"sale-link\"><a href=\"sale.jsp\" >Sale</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"mortgage-link\"><a href=\"mortgage.jsp\" >Mortgage</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"search-link\"><a href=\"search.jsp\" >Search</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a onclick=\"myFunction()\" href=\"#\">Logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<h1>Mangal Murti Jewellers</h1>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"pure-g \">\r\n");
      out.write("\t\t\t\t\t<div class=\"pure-u-1-1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pure-form pure-form-aligned\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ----------------------------------------------------- CUSTOMER START ------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t\t\t\t");

							    String cID = request.getParameter("id");
							    int customerID = Integer.parseInt(cID);
							    CustomerBean cBean = JdbcCustomerUtility.getCustomerById(customerID);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Customer Profile</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"pure-table pure-table-bordered\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th colspan=\"2\" style=\"text-align: center\">Customer Details</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 15em;\">Customer ID</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(cBean.getCustomerID());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Customer Name</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(cBean.getCustomerName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Customer Phone</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(cBean.getCustomerPhoneNum());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Customer Address</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(cBean.getCustomerAddress());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ------------------------------------------------------ CUSTOMER END -------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ------------------------------------------------------- SALE START --------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");

							    ArrayList<SaleTransactionBean> sBeanList = new JdbcCustomerUtility().fetchCustomerSaleDetails(cBean);
							    Iterator<SaleTransactionBean> iterator = sBeanList.iterator();
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Sale Transactions</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"pure-table pure-table-bordered\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Type</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Tag</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Weight</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Date of Sale</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>EMI</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								    while (iterator.hasNext())
								    {
								        SaleTransactionBean sBean = iterator.next();
								        ProductBean pBean = sBean.getProductBean();
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(pBean.getProductType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(pBean.getProductTag());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(pBean.getProductWeight());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(sBean.getSalePrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(sBean.getDateOfSale());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if(sBean.isEMI())
									{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><a class='iframe' href=\"");
      out.print(request.getContextPath());
      out.write("/salehistoryupdate.jsp?sTransID=");
      out.print(sBean.getSaleTransactionID());
      out.write("\">EMI Details</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
									else
									{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>NA</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								    if (iterator.hasNext())
								        {
								            sBean = iterator.next();
								            pBean = sBean.getProductBean();
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"pure-table-odd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(pBean.getProductType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(pBean.getProductTag());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(pBean.getProductWeight());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(sBean.getSalePrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(sBean.getDateOfSale());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if(sBean.isEMI())
										{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><a class='iframe' href=\"");
      out.print(request.getContextPath());
      out.write("/salehistoryupdate.jsp?sTransID=");
      out.print(sBean.getSaleTransactionID());
      out.write("\">EMI Details</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
										else
										{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>NA</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								    	}
								    }
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ------------------------------------------------------ SALE END -------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- --------------------------------------------------- MORTGAGE START ----------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");

								ArrayList<MortgageTransactionBean> mBeanList = new JdbcCustomerUtility().fetchCustomerMortgageDetails(cBean);
							    Iterator<MortgageTransactionBean> mBeanIter = mBeanList.iterator();
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Mortgage Transactions</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"pure-table pure-table-bordered\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Type</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Weight</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Description</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Product Image</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Loan Amount</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Loan Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Update Mortgage</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								    while (mBeanIter.hasNext())
								    {
								        MortgageTransactionBean mBean = mBeanIter.next();
								   	 	MortgageProductBean mpBean = mBean.getMbean();
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductWeight());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductDesc());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><a class=\"iframe\" href=\"");
      out.print(request.getContextPath());
      out.write("/MortgageImage?mortgageTransID=");
      out.print(mBean.getMortgageTransactionID());
      out.write("\">View Image</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mBean.getMortgageAmount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mBean.getMortgageDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><a class=\"iframe\" href=\"");
      out.print(request.getContextPath());
      out.write("/mortgagehistoryupdate.jsp?mTransID=");
      out.print(mBean.getMortgageTransactionID());
      out.write("\">Mortgage Details</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								    if (mBeanIter.hasNext())
								        {
								        	mBean = mBeanIter.next();
								            mpBean = mBean.getMbean();
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"pure-table-odd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductWeight());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductDesc());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mpBean.getProductPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><a class=\"iframe\" href=\"");
      out.print(request.getContextPath());
      out.write("/MortgageImage?mortgageTransID=");
      out.print(mBean.getMortgageTransactionID());
      out.write("\">View Image</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mBean.getMortgageAmount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(mBean.getMortgageDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><a class=\"iframe\" href=\"");
      out.print(request.getContextPath());
      out.write("/mortgagehistoryupdate.jsp?mTransID=");
      out.print(mBean.getMortgageTransactionID());
      out.write("\">Mortgage Details</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								    	}
								    }
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ---------------------------------------------------- MORTGAGE END ------------------------------------------------------------ -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"pure-control-group\" style=\"width: 15%; margin: 0px auto; margin-top: 1em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" name=\"Submit\" class=\"button-success pure-button\" value=\"Delete Old Images\" onclick=\"deleteImagesFromDb()\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"js/ui.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
