/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-09 08:53:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URL;
import java.net.URLClassLoader;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"A layout example with a side menu that hides on mobile, just like the Pure website.\">\n");
      out.write("\n");
      out.write("    <title>Mangal &nbsp;Murti</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pure-min.css\">\n");
      out.write("\n");
      out.write("    <!--[if lte IE 8]>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/layouts/side-menu-old-ie.css\">\n");
      out.write("    <![endif]-->\n");
      out.write("    <!--[if gt IE 8]><!-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/layouts/side-menu.css\">\n");
      out.write("    <!--<![endif]-->\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("    .center-text {\n");
      out.write("        text-align: center;\n");
      out.write("        padding-top: 5em;\n");
      out.write("    }\n");
      out.write("    .span-pad {\n");
      out.write("        padding: 0.4em;\n");
      out.write("    }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"layout\">\n");
      out.write("    <!-- Menu toggle -->\n");
      out.write("    <a href=\"#menu\" id=\"menuLink\" class=\"menu-link\">\n");
      out.write("        <!-- Hamburger icon -->\n");
      out.write("        <span></span>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <div id=\"menu\">\n");
      out.write("        <div class=\"pure-menu pure-menu-open\">\n");
      out.write("            <a class=\"pure-menu-heading\" style=\"text-transform:none; font-size:120%\" href=\"#\">\n");
      out.write("                JewelTrack<sup>tm</sup>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"main\">\n");
      out.write("        <div class=\"header\">\n");
      out.write("            <h1 style=\"margin-right: 1em\">Mangal Murti Jewellers</h1>\n");
      out.write("        </div>\n");
      out.write("\t\t\n");
      out.write("        <div class=\"content\">\n");
      out.write("           <div class=\"center-text\" >\n");
      out.write("           <form class=\"pure-form\" action=\"Login\" method=\"post\">\n");
      out.write("                <fieldset>\n");
      out.write("                    <input type=\"text\" placeholder=\"Email\" name=\"username\" required >\n");
      out.write("                    <div class=\"span-pad\"></div>\n");
      out.write("                    <input type=\"password\" placeholder=\"Password\" name=\"password\" required >\n");
      out.write("                    <div class=\"span-pad\"></div>\n");
      out.write("                    <button type=\"submit\" class=\"pure-button pure-button-primary\">Sign in</button>\n");
      out.write("                </fieldset>\n");
      out.write("            </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"js/ui.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
