/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-09 08:53:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Date;
import sale.SaleTransactionBean;
import java.util.Iterator;
import mortgage.MortgageTransactionBean;
import java.util.ArrayList;

public final class report_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1407531964000L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1407531964000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"A layout example with a side menu that hides on mobile, just like the Pure website.\">\r\n");
      out.write("\r\n");
      out.write("<title>Mangal &nbsp;Murti</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"css/pure-min.css\">\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 8]>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/layouts/side-menu-old-ie.css\">\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layouts/side-menu.css\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/offline-scripts/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/offline-scripts/jquery-ui-1.11.0.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".center-text {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".span-pad {\r\n");
      out.write("\tpadding: 0.4em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t\tvar x;\r\n");
      out.write("\t\tif (confirm(\"Do you want to logout ???\") == true) {\r\n");
      out.write("\t\t\twindow.location.replace(\"logout.jsp\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tx = \"You pressed Cancel!\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"demo\").innerHTML = x;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction pageEssentials() {\r\n");
      out.write("\t\tdocument.getElementById(\"report-link\").className = \"menu-item-divided pure-menu-selected\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"pageEssentials()\">\r\n");
      out.write("\t<div id=\"layout\">\r\n");
      out.write("\t\t<!-- Menu toggle -->\r\n");
      out.write("\t\t<a href=\"#menu\" id=\"menuLink\" class=\"menu-link\"> <!-- Hamburger icon -->\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Date JQuery Imports -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function dateChecker() {\r\n");
      out.write("\tvar something = document.getElementById(\"datepicker\").value;\r\n");
      out.write("\tvar something1 = document.getElementById(\"datepicker1\").value;\r\n");
      out.write("\tif(something == \"\" || something1 == \"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\talert('Please enter date !!!');\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("    $(\"#datepicker\").datepicker();\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("$(function() {\r\n");
      out.write("    $(\"#datepicker1\").datepicker();\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pure-min.css\">\r\n");
      out.write("<!-- Date JQuery Imports -->\r\n");
      out.write("\t");

		Boolean isloggedin = (Boolean) session.getAttribute("isloggedin");
		if(isloggedin == null || isloggedin == Boolean.FALSE)
		{
		    out.write("<script type='text/javascript'>\n");
		    out.write("alert(' Your session has expired. Please login again. ');\n");
		    out.write("setTimeout(function(){window.location.href='index.jsp'},0);");
		    out.write("</script>\n");	    
		}
	
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("\t<div class=\"pure-menu pure-menu-open\">\r\n");
      out.write("\t\t<a class=\"pure-menu-heading\"\r\n");
      out.write("\t\t\tstyle=\"text-transform: none; font-size: 120%\" href=\"#\">JewelTrack<sup>tm</sup></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"dashboard-link\"><a href=\"dashboard.jsp\" >Home</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"report-link\"><a href=\"report.jsp\" >Report</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"\" id=\"inventory-link\"><a href=\"inventory.jsp\" >Inventory</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"\" id=\"sale-link\"><a href=\"sale.jsp\" >Sale</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"mortgage-link\"><a href=\"mortgage.jsp\" >Mortgage</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"search-link\"><a href=\"search.jsp\" >Search</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a onclick=\"myFunction()\" href=\"#\">Logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<h1>Mangal Murti Jewellers</h1>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"pure-g\">\r\n");
      out.write("\t\t\t\t\t<form action=\"ReportServ\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pure-u-1-1\" style=\"text-align:center; margin-left:130px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pure-form pure-form-aligned\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"pure-control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"date\">From Date</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"datepicker\" type=\"text\" placeholder=\"Date\" autocomplete=\"off\" name=\"fromDate\" required=\"required\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"pure-control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"date\">To Date</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"datepicker1\" type=\"text\" placeholder=\"Date\" autocomplete=\"off\" name=\"toDate\" required=\"required\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"pure-control-group\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span style=\"padding:30px;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"option-three\" class=\"pure-radio\">Sale</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"option-three\" type=\"radio\" name=\"optionsRadios\" value=\"sale\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"option-two\" class=\"pure-radio\" style=\"text-align:left; padding-left:10px; width:65px;\">Mortgage</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"option-two\" type=\"radio\" name=\"optionsRadios\" value=\"mortgage\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"pure-control-group\" style=\"text-align:right; padding-right:80px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" style=\"padding: 0.5em 2em 0.5em 2em;\" name=\"Submit\" class=\"button-success pure-button\" onclick=\"dateChecker()\" value=\"Show Reports\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!-- ------------------------------- Data Display Starts here ----------------------------- -->\r\n");
      out.write("\t\t\t\t\t<div class=\"pure-u-1-1\">\r\n");
      out.write("\t\t\t\t\t");

						String fromDate = (String) request.getAttribute("fromDate");
						String toDate = (String) request.getAttribute("toDate");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"pure-form pure-form-aligned\">\r\n");
      out.write("\t\t\t\t\t");

					    ArrayList<SaleTransactionBean> sArray = new ArrayList<SaleTransactionBean>();
					    ArrayList<MortgageTransactionBean> mArray = new ArrayList<MortgageTransactionBean>();

					    if (request.getAttribute("sarray") != null)
					    {

					        sArray = (ArrayList<SaleTransactionBean>)request.getAttribute("sarray");
					        Iterator sarrayIter = sArray.iterator();
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3>Sale Transactions Report from ");
      out.print(fromDate);
      out.write(" to ");
      out.print(toDate);
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t<table class=\"pure-table pure-table-bordered\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Customer Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Product Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Date of Sale</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t");

						    SaleTransactionBean sbean = new SaleTransactionBean();
						        while (sarrayIter.hasNext())
						        {
						            sbean = (SaleTransactionBean)sarrayIter.next();
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"customerdetail.jsp?id=");
      out.print(sbean.getCustomerBean().getCustomerID());
      out.write('"');
      out.write('>');
      out.print(sbean.getCustomerBean().getCustomerName());
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(sbean.getSalePrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(sbean.getDateOfSale());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

						    }
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					    }
					    else if (request.getAttribute("marray") != null)
					    {
					        mArray = (ArrayList<MortgageTransactionBean>)request.getAttribute("marray");
					        Iterator marrrayIter = mArray.iterator();
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3>Mortgage Transactions Report from ");
      out.print(fromDate);
      out.write(" to ");
      out.print(toDate);
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t<table class=\"pure-table pure-table-bordered\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Customer Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Mortgage Amount</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Mortgage Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t");

						    MortgageTransactionBean mbean = new MortgageTransactionBean();
						        while (marrrayIter.hasNext())
						        {
						            mbean = (MortgageTransactionBean)marrrayIter.next();
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"customerdetail.jsp?id=");
      out.print(mbean.getCbean().getCustomerID());
      out.write('"');
      out.write('>');
      out.print(mbean.getCbean().getCustomerName());
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(mbean.getMortgageAmount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(mbean.getMortgageDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

						    }
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t");

					    }
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"js/ui.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
