/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-09 09:06:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.ArrayList;
import customer.CustomerBean;
import search.CustomerSearchBean;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1407531964000L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1407531964000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"A layout example with a side menu that hides on mobile, just like the Pure website.\">\r\n");
      out.write("\r\n");
      out.write("    <title>Mangal &nbsp;Murti</title>\r\n");
      out.write("\r\n");
      out.write("    <!--[if lte IE 8]>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/layouts/side-menu-old-ie.css\">\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <!--[if gt IE 8]><!-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/layouts/side-menu.css\">\r\n");
      out.write("    <!--<![endif]-->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .center-text {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding-top: 5em;\r\n");
      out.write("    }\r\n");
      out.write("    .span-pad {\r\n");
      out.write("        padding: 0.4em;\r\n");
      out.write("    }\r\n");
      out.write("    .button-success {\r\n");
      out.write("\t\tbackground: rgb(28, 184, 65);\r\n");
      out.write("\t}\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function myFunction() {\r\n");
      out.write("        var x;\r\n");
      out.write("        if (confirm(\"Do you want to logout ???\") == true) {\r\n");
      out.write("        \twindow.location.replace(\"logout.jsp\");\r\n");
      out.write("        } else {\r\n");
      out.write("            x = \"You pressed Cancel!\";\r\n");
      out.write("        }\r\n");
      out.write("        document.getElementById(\"demo\").innerHTML = x;\r\n");
      out.write("    }\r\n");
      out.write("    function pageEssentials() {\r\n");
      out.write("    \tdocument.getElementById(\"search-link\").className = \"menu-item-divided pure-menu-selected\";\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

	ArrayList<CustomerBean> list = null;
	if(session.getAttribute("List")!=null)
	{
		list = (ArrayList<CustomerBean>)session.getAttribute("List");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body onload=\"pageEssentials()\">\r\n");
      out.write("<div id=\"layout\">\r\n");
      out.write("    <!-- Menu toggle -->\r\n");
      out.write("    <a href=\"#menu\" id=\"menuLink\" class=\"menu-link\">\r\n");
      out.write("        <!-- Hamburger icon -->\r\n");
      out.write("        <span></span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Date JQuery Imports -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function dateChecker() {\r\n");
      out.write("\tvar something = document.getElementById(\"datepicker\").value;\r\n");
      out.write("\tvar something1 = document.getElementById(\"datepicker1\").value;\r\n");
      out.write("\tif(something == \"\" || something1 == \"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\talert('Please enter date !!!');\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("    $(\"#datepicker\").datepicker();\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("$(function() {\r\n");
      out.write("    $(\"#datepicker1\").datepicker();\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pure-min.css\">\r\n");
      out.write("<!-- Date JQuery Imports -->\r\n");
      out.write("\t");

		Boolean isloggedin = (Boolean) session.getAttribute("isloggedin");
		if(isloggedin == null || isloggedin == Boolean.FALSE)
		{
		    out.write("<script type='text/javascript'>\n");
		    out.write("alert(' Your session has expired. Please login again. ');\n");
		    out.write("setTimeout(function(){window.location.href='index.jsp'},0);");
		    out.write("</script>\n");	    
		}
	
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("\t<div class=\"pure-menu pure-menu-open\">\r\n");
      out.write("\t\t<a class=\"pure-menu-heading\"\r\n");
      out.write("\t\t\tstyle=\"text-transform: none; font-size: 120%\" href=\"#\">JewelTrack<sup>tm</sup></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"dashboard-link\"><a href=\"dashboard.jsp\" >Home</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"report-link\"><a href=\"report.jsp\" >Report</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"\" id=\"inventory-link\"><a href=\"inventory.jsp\" >Inventory</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"\" id=\"sale-link\"><a href=\"sale.jsp\" >Sale</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"mortgage-link\"><a href=\"mortgage.jsp\" >Mortgage</a></li>\r\n");
      out.write("\t\t\t<li class=\"\" id=\"search-link\"><a href=\"search.jsp\" >Search</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a onclick=\"myFunction()\" href=\"#\">Logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<h1>Mangal Murti Jewellers</h1>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"content\" style=\"padding-right: 8em\">\r\n");
      out.write("        <div class=\"pure-g\" >\r\n");
      out.write("\t\t\t\t\t<form action=\"CustomerSearch\" method=\"get\" style=\"margin:0px auto\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pure-u-1-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pure-form pure-form-aligned\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pure-control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"tags\">Customer Name: </label> <input name=\"customerName\" id=\"tags\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Customer Name\" required=\"required\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pure-control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"number\">Customer Number: </label> <input name=\"customerNumber\" id=\"number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"Customer Number\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pure-control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"address\">Customer Address</label> <input id=\"address\" name=\"customerAddress\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"Customer Address\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pure-u-2-1\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" style=\"margin-left:10em; padding: 0.5em 2em 0.5em 2em;\" name=\"Submit\" class=\"button-success pure-button\" value=\"Search\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("          </fieldset>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"js/ui.js\"></script>\r\n");

	if(list!=null)
	{

      out.write("\r\n");
      out.write("<div  class=\"pure-u-2-1\" style=\" padding-top: 3em;\">\r\n");

		Iterator<CustomerBean> iter = list.iterator();
		
      out.write("\r\n");
      out.write("\t\t<table class=\"pure-table pure-table-bordered\" style=\"margin : 0px auto;\">\r\n");
      out.write("    <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Name</th>\r\n");
      out.write("            <th>Phone no.</th>\r\n");
      out.write("            <th>Address</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("\r\n");
      out.write("    <tbody>\r\n");
      out.write("        <tr>\r\n");
      out.write("\t\t");

		while(iter.hasNext()) 
		{
		    CustomerBean csbean = iter.next();

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("            <td><a href=\"customerdetail.jsp?id=");
      out.print(csbean.getCustomerID() );
      out.write('"');
      out.write('>');
      out.print(csbean.getCustomerName() );
      out.write("</a></td>\r\n");
      out.write("            <td>");
      out.print(csbean.getCustomerPhoneNum() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(csbean.getCustomerAddress() );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t");
	
		}
		
	
      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
